# Generated by Django 5.1.1 on 2024-09-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentrent',
            name='featured',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='featured',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='featured',
            field=models.IntegerField(default=0),
        ),
    ]
