# Generated by Django 5.1.1 on 2024-09-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_apartmentrent_featured_apartmentsale_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentrent',
            name='pic_thumbnail',
            field=models.ImageField(default='img1.jpg', upload_to='medios'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='pic',
            field=models.ImageField(default='img1.jpg', upload_to='medios'),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='pic_thumbnail',
            field=models.ImageField(default='img1.jpg', upload_to='medios'),
        ),
        migrations.AddField(
            model_name='room',
            name='pic_thumbnail',
            field=models.ImageField(default='img1.jpg', upload_to='medios'),
        ),
    ]
