# Generated by Django 5.1.1 on 2024-09-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_apartmentrent_pic_thumbnail_apartmentsale_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentrent',
            old_name='price_rent',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='apartmentsale',
            old_name='price_sale',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='price_room',
            new_name='price',
        ),
    ]
