# Generated by Django 5.1.1 on 2024-09-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_rename_price_rent_apartmentrent_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentrent',
            name='price_units',
            field=models.CharField(default='€/mes', max_length=20),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='price_units',
            field=models.CharField(default='€/mes', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='price_units',
            field=models.CharField(default='€/mes', max_length=20),
        ),
    ]
