# Generated by Django 5.1.1 on 2024-09-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_apartmentrent_price_units_apartmentsale_price_units_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentsale',
            old_name='has_garage',
            new_name='garage',
        ),
        migrations.RenameField(
            model_name='apartmentsale',
            old_name='has_garden',
            new_name='garden',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_units',
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='deposit',
            field=models.CharField(blank=True, choices=[('one_month', '1 mes'), ('two_months', '2 meses'), ('three_months', '3 meses')], max_length=30),
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='energy_certificate',
            field=models.CharField(blank=True, choices=[('unavailable', 'Aún no disponible'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('in_progress', 'En trámite'), ('exempt', 'Inmueble exento')], max_length=30),
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='size_net',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='air_conditioning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='builtin_wardrobes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='energy_certificate',
            field=models.CharField(blank=True, choices=[('unavailable', 'Aún no disponible'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('in_progress', 'En trámite'), ('exempt', 'Inmueble exento')], max_length=30),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='floor',
            field=models.CharField(choices=[('ground_floor', 'Planta baja'), ('1', 'Planta primera'), ('2', 'Planta segunda'), ('3', 'Planta tercera'), ('4', 'Planta cuarta'), ('5', 'Planta quinta')], default='ground_floor', max_length=100),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='good_condition',
            field=models.CharField(choices=[('new', 'Obra nueva'), ('good_condition', 'Buen estado'), ('to_reform', 'A reformar')], default='good_condition', max_length=100),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='luxury',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='n_bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Piso'), ('attic', 'Ático'), ('duplex', 'Dúplex'), ('independent', 'Chalet independiente'), ('semi_detached', 'Chalet adosado'), ('rustic', 'Casa rústica')], default='apartment', max_length=100),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='size_net',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='storage_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentsale',
            name='terrace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='price_unit',
            field=models.CharField(choices=[('euro', '€'), ('euro_per_month', '€/mes')], default='euro_per_month', max_length=20),
        ),
        migrations.AlterField(
            model_name='apartmentrent',
            name='price_units',
            field=models.CharField(default='euro_per_month', max_length=20),
        ),
        migrations.AlterField(
            model_name='apartmentsale',
            name='price_units',
            field=models.CharField(default='euro', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='deposit',
            field=models.CharField(blank=True, choices=[('one_month', '1 mes'), ('two_months', '2 meses'), ('three_months', '3 meses')], max_length=30),
        ),
    ]
